confluent kafka topic create cond_cap_sec_bal --cluster lkc-9gnvpy
confluent kafka topic create exec_comp_stat --cluster lkc-9gnvpy
confluent kafka topic create corp_bond_bal --cluster lkc-9gnvpy
confluent kafka topic create short_bond_bal --cluster lkc-9gnvpy
confluent kafka topic create com_paper_bal --cluster lkc-9gnvpy
confluent kafka topic create debt_sec_perf --cluster lkc-9gnvpy
confluent kafka topic create dir_aud_comp_gm --cluster lkc-9gnvpy
confluent kafka topic create dir_aud_comp_type --cluster lkc-9gnvpy
confluent kafka topic create total_shares --cluster lkc-9gnvpy
confluent kafka topic create non_audit_contr --cluster lkc-9gnvpy
confluent kafka topic create out_dir_stat --cluster lkc-9gnvpy
confluent kafka topic create new_cap_sec_bal --cluster lkc-9gnvpy
confluent kafka topic create cap_inc_dec_stat --cluster lkc-9gnvpy
confluent kafka topic create dividend_info --cluster lkc-9gnvpy
confluent kafka topic create treasury_stock --cluster lkc-9gnvpy
confluent kafka topic create major_shareholder --cluster lkc-9gnvpy
confluent kafka topic create major_share_chg --cluster lkc-9gnvpy
confluent kafka topic create minority_share --cluster lkc-9gnvpy
confluent kafka topic create exec_status --cluster lkc-9gnvpy
confluent kafka topic create emp_status --cluster lkc-9gnvpy
confluent kafka topic create indv_dir_aud_comp --cluster lkc-9gnvpy
confluent kafka topic create all_dir_aud_comp --cluster lkc-9gnvpy
confluent kafka topic create top5_exec_comp --cluster lkc-9gnvpy
confluent kafka topic create other_corp_inv --cluster lkc-9gnvpy
confluent kafka topic create single_corp_fin --cluster lkc-9gnvpy